services:
  - type: web
    name: DJ-Dart-render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=8000 --server.enableCORS=false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"